### ISSUE TITLE
Off by one?

### ISSUE THREAD

**Issue by dstarh** [ertugrulcetin/GlueList#1]
Am I crazy or is there an off by one error here?

```
    private void rangeCheckForAdd(int index) {

        if (index > size || index < 0) {
            throw new ArrayIndexOutOfBoundsException(index);
        }
    }
```
A list of size 1 does not have anything at index 1

**Comment by ertugrulcetin** [comment]
Nope there is no problem at all.
It's dynamically growing(just like ArrayList) so the expression **index > size** valid.

If you look ArrayList source code, you will see this following method:

    /**
     * A version of rangeCheck used by add and addAll.
     */
   ```
 private void rangeCheckForAdd(int index) {
        if (index > size || index < 0)
            throw new IndexOutOfBoundsException(outOfBoundsMsg(index));
    }
```
